define(['dart_sdk'], (function load__packages__intl__date_time_patterns(dart_sdk) {
  'use strict';
  const core = dart_sdk.core;
  const dart = dart_sdk.dart;
  const dartx = dart_sdk.dartx;
  var date_time_patterns = Object.create(dart.library);
  var StringL = () => (StringL = dart.constFn(dart.legacy(core.String)))();
  const CT = Object.create(null);
  dart.defineLazy(CT, {
    get C1() {
      return C1 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd-MM", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM-y", "yMd", "y-MM-dd", "yMEd", "EEE y-MM-dd", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C2() {
      return C2 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "M/d", "MEd", "EEE፣ M/d", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "EEE፣ MMM d", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE፣ MMMM d", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE፣ d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE፣ MMM d y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE ፣d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C3() {
      return C3 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/‏M", "MEd", "EEE، d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE، d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE، d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M‏/y", "yMd", "d‏/M‏/y", "yMEd", "EEE، d/‏M/‏y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE، d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE، d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C4() {
      return C4 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd.MM", "MEd", "dd.MM, EEE", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "d MMM, EEE", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "d MMMM, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "dd.MM.y", "yMEd", "dd.MM.y, EEE", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "d MMM y, EEE", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "d MMMM y, EEEE", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C5() {
      return C5 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M", "MEd", "EEE, d.M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M.y", "yMd", "d.M.y", "yMEd", "EEE, d.M.y", "yMMM", "LLL y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "LLLL y", "yMMMMd", "d MMMM y 'г'.", "yMMMMEEEEd", "EEEE, d MMMM y 'г'.", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm.ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C6() {
      return C6 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.MM", "MEd", "EEE, d.MM", "MMM", "MM", "MMMd", "d.MM", "MMMEd", "EEE, d.MM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y 'г'.", "yM", "MM.y 'г'.", "yMd", "d.MM.y 'г'.", "yMEd", "EEE, d.MM.y 'г'.", "yMMM", "MM.y 'г'.", "yMMMd", "d.MM.y 'г'.", "yMMMEd", "EEE, d.MM.y 'г'.", "yMMMM", "MMMM y 'г'.", "yMMMMd", "d MMMM y 'г'.", "yMMMMEEEEd", "EEEE, d MMMM y 'г'.", "yQQQ", "QQQ y 'г'.", "yQQQQ", "QQQQ y 'г'.", "H", "H 'ч'.", "Hm", "H:mm 'ч'.", "Hms", "H:mm:ss 'ч'.", "j", "H 'ч'.", "jm", "H:mm 'ч'.", "jms", "H:mm:ss 'ч'.", "jmv", "HH:mm 'ч'. v", "jmz", "HH:mm 'ч'. z", "jz", "H 'ч'. z", "m", "m", "ms", "m:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C7() {
      return C7 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d-M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM, y", "yMMMEd", "EEE, d MMM, y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM, y", "yMMMMEEEEd", "EEEE, d MMMM, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C8() {
      return C8 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "MM", "Md", "dd/MM", "MEd", "EEE dd/MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd/MM/y", "yMEd", "EEE dd/MM/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C9() {
      return C9 = dart.constMap(StringL(), StringL(), ["d", "d.", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M.", "MEd", "EEE, d.M.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE, d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE, d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y.", "yM", "MM/y", "yMd", "d.M.y.", "yMEd", "EEE, d.M.y.", "yMMM", "MMM y.", "yMMMd", "d. MMM y.", "yMMMEd", "EEE, d. MMM y.", "yMMMM", "LLLL y.", "yMMMMd", "d. MMMM y.", "yMMMMEEEEd", "EEEE, d. MMMM y.", "yQQQ", "QQQ y.", "yQQQQ", "QQQQ y.", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm (v)", "jmz", "HH:mm (z)", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C10() {
      return C10 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "LLL 'de' y", "yMMMd", "d MMM 'de' y", "yMMMEd", "EEE, d MMM y", "yMMMM", "LLLL 'de' y", "yMMMMd", "d MMMM 'de' y", "yMMMMEEEEd", "EEEE, d MMMM 'de' y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "H:mm v", "jmz", "H:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C11() {
      return C11 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "M/d", "MEd", "EEE, M/d", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "EEE, MMM d", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE, MMMM d", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "M/d/y", "yMEd", "EEE, M/d/y", "yMMM", "MMM y", "yMMMd", "MMM d, y", "yMMMEd", "EEE, MMM d, y", "yMMMM", "MMMM y", "yMMMMd", "MMMM d, y", "yMMMMEEEEd", "EEEE, MMMM d, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C12() {
      return C12 = dart.constMap(StringL(), StringL(), ["d", "d.", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d. M.", "MEd", "EEE d. M.", "MMM", "LLL", "MMMd", "d. M.", "MMMEd", "EEE d. M.", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d. M. y", "yMEd", "EEE d. M. y", "yMMM", "LLLL y", "yMMMd", "d. M. y", "yMMMEd", "EEE d. M. y", "yMMMM", "LLLL y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "H:mm v", "jmz", "H:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C13() {
      return C13 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C14() {
      return C14 = dart.constMap(StringL(), StringL(), ["d", "d.", "E", "ccc", "EEEE", "cccc", "LLL", "MMM", "LLLL", "MMMM", "M", "M", "Md", "d/M", "MEd", "EEE d/M", "MMM", "MMM", "MMMd", "d. MMM", "MMMEd", "EEE d. MMM", "MMMM", "MMMM", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE d/M/y", "yMMM", "MMM y", "yMMMd", "d. MMM y", "yMMMEd", "EEE d. MMM y", "yMMMM", "MMMM y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE 'den' d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH.mm", "Hms", "HH.mm.ss", "j", "HH", "jm", "HH.mm", "jms", "HH.mm.ss", "jmv", "HH.mm v", "jmz", "HH.mm z", "jz", "HH z", "m", "m", "ms", "mm.ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C15() {
      return C15 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M.", "MEd", "EEE, d.M.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE, d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE, d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M.y", "yMd", "d.M.y", "yMEd", "EEE, d.M.y", "yMMM", "MMM y", "yMMMd", "d. MMM y", "yMMMEd", "EEE, d. MMM y", "yMMMM", "MMMM y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE, d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH 'Uhr'", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH 'Uhr'", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH 'Uhr' z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C16() {
      return C16 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "MMM", "LLLL", "MMMM", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "MMM", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "MMMM", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "LLLL y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C17() {
      return C17 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd/MM/y", "yMEd", "EEE, dd/MM/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C18() {
      return C18 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "MM-dd", "MEd", "EEE, MM-dd", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "EEE, MMM d", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE, MMMM d", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "y-MM-dd", "yMEd", "EEE, y-MM-dd", "yMMM", "MMM y", "yMMMd", "MMM d, y", "yMMMEd", "EEE, MMM d, y", "yMMMM", "MMMM y", "yMMMMd", "MMMM d, y", "yMMMMEEEEd", "EEEE, MMMM d, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C19() {
      return C19 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd/MM", "MEd", "EEE dd/MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd/MM/y", "yMEd", "EEE, dd/MM/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C20() {
      return C20 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C21() {
      return C21 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd/MM", "MEd", "EEE, dd/MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM, y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C22() {
      return C22 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd/MM", "MEd", "EEE, dd/MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd/MM/y", "yMEd", "EEE, dd/MM/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C23() {
      return C23 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "MM/dd", "MEd", "EEE, MM/dd", "MMM", "LLL", "MMMd", "dd MMM", "MMMEd", "EEE, dd MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, dd MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "y/MM/dd", "yMEd", "EEE, y/MM/dd", "yMMM", "MMM y", "yMMMd", "dd MMM y", "yMMMEd", "EEE, dd MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C24() {
      return C24 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d 'de' MMMM", "MMMMEEEEd", "EEEE, d 'de' MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM 'de' y", "yMMMMd", "d 'de' MMMM 'de' y", "yMMMMEEEEd", "EEEE, d 'de' MMMM 'de' y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ 'de' y", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "H:mm v", "jmz", "H:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C25() {
      return C25 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d 'de' MMMM", "MMMMEEEEd", "EEEE, d 'de' MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE d/M/y", "yMMM", "MMMM 'de' y", "yMMMd", "d 'de' MMMM 'de' y", "yMMMEd", "EEE, d 'de' MMM 'de' y", "yMMMM", "MMMM 'de' y", "yMMMMd", "d 'de' MMMM 'de' y", "yMMMMEEEEd", "EEEE, d 'de' MMMM 'de' y", "yQQQ", "QQQ 'de' y", "yQQQQ", "QQQQ 'de' y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "H:mm v", "jmz", "H:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C26() {
      return C26 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d 'de' MMM", "MMMM", "LLLL", "MMMMd", "d 'de' MMMM", "MMMMEEEEd", "EEEE, d 'de' MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMMM 'de' y", "yMMMd", "d 'de' MMMM 'de' y", "yMMMEd", "EEE, d 'de' MMMM 'de' y", "yMMMM", "MMMM 'de' y", "yMMMMd", "d 'de' MMMM 'de' y", "yMMMMEEEEd", "EEEE, d 'de' MMMM 'de' y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ 'de' y", "H", "HH", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "HH", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "H:mm v", "jmz", "H:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C27() {
      return C27 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d 'de' MMM", "MMMM", "LLLL", "MMMMd", "d 'de' MMMM", "MMMMEEEEd", "EEEE, d 'de' MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMMM 'de' y", "yMMMd", "d 'de' MMMM 'de' y", "yMMMEd", "EEE, d 'de' MMMM 'de' y", "yMMMM", "MMMM 'de' y", "yMMMMd", "d 'de' MMMM 'de' y", "yMMMMEEEEd", "EEEE, d 'de' MMMM 'de' y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ 'de' y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C28() {
      return C28 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "MMMM", "LLLL", "MMMM", "M", "M", "Md", "d.M", "MEd", "EEE, d.M", "MMM", "MMMM", "MMMd", "d. MMM", "MMMEd", "EEE, d. MMM", "MMMM", "MMMM", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE, d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M.y", "yMd", "d.M.y", "yMEd", "EEE, d.M.y", "yMMM", "MMM y", "yMMMd", "d. MMM y", "yMMMEd", "EEE, d. MMMM y", "yMMMM", "MMMM y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE, d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C29() {
      return C29 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "M/d", "MEd", "M/d, EEE", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "MMM d, EEE", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "MMMM d, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y/M", "yMd", "y/M/d", "yMEd", "y/M/d, EEE", "yMMM", "y MMM", "yMMMd", "y MMM d", "yMMMEd", "y MMM d, EEE", "yMMMM", "y('e')'ko' MMMM", "yMMMMd", "y('e')'ko' MMMM'ren' d", "yMMMMEEEEd", "y('e')'ko' MMMM'ren' d('a'), EEEE", "yQQQ", "y('e')'ko' QQQ", "yQQQQ", "y('e')'ko' QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH (z)", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C30() {
      return C30 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "M/d", "MEd", "EEE M/d", "MMM", "LLL", "MMMd", "d LLL", "MMMEd", "EEE d LLL", "MMMM", "LLLL", "MMMMd", "d LLLL", "MMMMEEEEd", "EEEE d LLLL", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y/M", "yMd", "y/M/d", "yMEd", "EEE y/M/d", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm (z)", "jz", "H (z)", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C31() {
      return C31 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M.", "MEd", "EEE d.M.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "ccc d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "cccc d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "L.y", "yMd", "d.M.y", "yMEd", "EEE d.M.y", "yMMM", "LLL y", "yMMMd", "d. MMM y", "yMMMEd", "EEE d. MMM y", "yMMMM", "LLLL y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "H.mm", "Hms", "H.mm.ss", "j", "H", "jm", "H.mm", "jms", "H.mm.ss", "jmv", "H.mm v", "jmz", "H.mm z", "jz", "H z", "m", "m", "ms", "m.ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C32() {
      return C32 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "EEE", "EEEE", "EEEE", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd/MM", "MEd", "EEE dd/MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd/MM/y", "yMEd", "EEE dd/MM/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH 'h'", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH 'h'", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH 'h' z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C33() {
      return C33 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "EEE", "EEEE", "EEEE", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "M-d", "MEd", "EEE M-d", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "y-MM-dd", "yMEd", "EEE y-MM-dd", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH 'h'", "Hm", "HH 'h' mm", "Hms", "HH 'h' mm 'min' ss 's'", "j", "HH 'h'", "jm", "HH 'h' mm", "jms", "HH 'h' mm 'min' ss 's'", "jmv", "HH 'h' mm v", "jmz", "HH 'h' mm z", "jz", "HH 'h' z", "m", "m", "ms", "mm 'min' ss 's'", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C34() {
      return C34 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "LL", "Md", "dd/MM", "MEd", "EEE dd/MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd/MM/y", "yMEd", "EEE dd/MM/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C35() {
      return C35 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d 'de' MMM", "MMMEd", "EEE, d 'de' MMM", "MMMM", "LLLL", "MMMMd", "d 'de' MMMM", "MMMMEEEEd", "EEEE, d 'de' MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM 'de' y", "yMMMd", "d/MM/y", "yMMMEd", "EEE, d/MM/y", "yMMMM", "MMMM 'de' y", "yMMMMd", "d 'de' MMMM 'de' y", "yMMMMEEEEd", "EEEE, d 'de' MMMM 'de' y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ 'de' y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C36() {
      return C36 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "EEE", "EEEE", "EEEE", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M.", "MEd", "EEE, d.M.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-M", "yMd", "d.M.y", "yMEd", "EEE, y-M-d", "yMMM", "MMM y", "yMMMd", "y MMM d", "yMMMEd", "EEE, d. MMM y", "yMMMM", "MMMM y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE, d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "H", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C37() {
      return C37 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM, y", "yMMMEd", "EEE, d MMM, y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM, y", "yMMMMEEEEd", "EEEE, d MMMM, y", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C38() {
      return C38 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "y MMMM", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C39() {
      return C39 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M", "MEd", "EEE, d.M", "MMM", "LLL", "MMMd", "d בMMM", "MMMEd", "EEE, d בMMM", "MMMM", "LLLL", "MMMMd", "d בMMMM", "MMMMEEEEd", "EEEE, d בMMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M.y", "yMd", "d.M.y", "yMEd", "EEE, d.M.y", "yMMM", "MMM y", "yMMMd", "d בMMM y", "yMMMEd", "EEE, d בMMM y", "yMMMM", "MMMM y", "yMMMMd", "d בMMMM y", "yMMMMEEEEd", "EEEE, d בMMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C40() {
      return C40 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C41() {
      return C41 = dart.constMap(StringL(), StringL(), ["d", "d.", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L.", "Md", "dd. MM.", "MEd", "EEE, dd. MM.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE, d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE, d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y.", "yM", "MM. y.", "yMd", "dd. MM. y.", "yMEd", "EEE, dd. MM. y.", "yMMM", "LLL y.", "yMMMd", "d. MMM y.", "yMMMEd", "EEE, d. MMM y.", "yMMMM", "LLLL y.", "yMMMMd", "d. MMMM y.", "yMMMMEEEEd", "EEEE, d. MMMM y.", "yQQQ", "QQQ y.", "yQQQQ", "QQQQ y.", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH (z)", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C42() {
      return C42 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "M. d.", "MEd", "M. d., EEE", "MMM", "LLL", "MMMd", "MMM d.", "MMMEd", "MMM d., EEE", "MMMM", "LLLL", "MMMMd", "MMMM d.", "MMMMEEEEd", "MMMM d., EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y.", "yM", "y. M.", "yMd", "y. MM. dd.", "yMEd", "y. MM. dd., EEE", "yMMM", "y. MMM", "yMMMd", "y. MMM d.", "yMMMEd", "y. MMM d., EEE", "yMMMM", "y. MMMM", "yMMMMd", "y. MMMM d.", "yMMMMEEEEd", "y. MMMM d., EEEE", "yQQQ", "y. QQQ", "yQQQQ", "y. QQQQ", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C43() {
      return C43 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd.MM", "MEd", "dd.MM, EEE", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "d MMM, EEE", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "d MMMM, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "dd.MM.y", "yMEd", "d.MM.y թ., EEE", "yMMM", "y թ. LLL", "yMMMd", "d MMM, y թ.", "yMMMEd", "y թ. MMM d, EEE", "yMMMM", "y թ․ LLLL", "yMMMMd", "d MMMM, y թ.", "yMMMMEEEEd", "y թ. MMMM d, EEEE", "yQQQ", "y թ. QQQ", "yQQQQ", "y թ. QQQQ", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C44() {
      return C44 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH.mm", "Hms", "HH.mm.ss", "j", "HH", "jm", "HH.mm", "jms", "HH.mm.ss", "jmv", "HH.mm v", "jmz", "HH.mm z", "jz", "HH z", "m", "m", "ms", "mm.ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C45() {
      return C45 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M.", "MEd", "EEE, d.M.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE, d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE, d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M. y", "yMd", "d.M.y", "yMEd", "EEE, d.M.y", "yMMM", "MMM y", "yMMMd", "d. MMM y", "yMMMEd", "EEE, d. MMM y", "yMMMM", "MMMM y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE, d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "v – HH:mm", "jmz", "z – HH:mm", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C46() {
      return C46 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C47() {
      return C47 = dart.constMap(StringL(), StringL(), ["d", "d日", "E", "ccc", "EEEE", "cccc", "LLL", "M月", "LLLL", "M月", "M", "M月", "Md", "M/d", "MEd", "M/d(EEE)", "MMM", "M月", "MMMd", "M月d日", "MMMEd", "M月d日(EEE)", "MMMM", "M月", "MMMMd", "M月d日", "MMMMEEEEd", "M月d日EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y年", "yM", "y/M", "yMd", "y/M/d", "yMEd", "y/M/d(EEE)", "yMMM", "y年M月", "yMMMd", "y年M月d日", "yMMMEd", "y年M月d日(EEE)", "yMMMM", "y年M月", "yMMMMd", "y年M月d日", "yMMMMEEEEd", "y年M月d日EEEE", "yQQQ", "y/QQQ", "yQQQQ", "y年QQQQ", "H", "H時", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H時", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "H:mm v", "jmz", "H:mm z", "jz", "H時 z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C48() {
      return C48 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M", "MEd", "EEE, d.M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M.y", "yMd", "d.M.y", "yMEd", "EEE, d.M.y", "yMMM", "MMM. y", "yMMMd", "d MMM. y", "yMMMEd", "EEE, d MMM. y", "yMMMM", "MMMM, y", "yMMMMd", "d MMMM, y", "yMMMMEEEEd", "EEEE, d MMMM, y", "yQQQ", "QQQ, y", "yQQQQ", "QQQQ, y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C49() {
      return C49 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd.MM", "MEd", "dd.MM, EEE", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "d MMM, EEE", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "d MMMM, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "dd.MM.y", "yMEd", "dd.MM.y, EEE", "yMMM", "y 'ж'. MMM", "yMMMd", "y 'ж'. d MMM", "yMMMEd", "y 'ж'. d MMM, EEE", "yMMMM", "y 'ж'. MMMM", "yMMMMd", "y 'ж'. d MMMM", "yMMMMEEEEd", "y 'ж'. d MMMM, EEEE", "yQQQ", "y 'ж'. QQQ", "yQQQQ", "y 'ж'. QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C50() {
      return C50 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C51() {
      return C51 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "d/M, EEE", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, M/d/y", "yMMM", "MMM y", "yMMMd", "MMM d,y", "yMMMEd", "EEE, MMM d, y", "yMMMM", "MMMM y", "yMMMMd", "MMMM d, y", "yMMMMEEEEd", "EEEE, MMMM d, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C52() {
      return C52 = dart.constMap(StringL(), StringL(), ["d", "d일", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "M월", "Md", "M. d.", "MEd", "M. d. (EEE)", "MMM", "LLL", "MMMd", "MMM d일", "MMMEd", "MMM d일 (EEE)", "MMMM", "LLLL", "MMMMd", "MMMM d일", "MMMMEEEEd", "MMMM d일 EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y년", "yM", "y. M.", "yMd", "y. M. d.", "yMEd", "y. M. d. (EEE)", "yMMM", "y년 MMM", "yMMMd", "y년 MMM d일", "yMMMEd", "y년 MMM d일 (EEE)", "yMMMM", "y년 MMMM", "yMMMMd", "y년 MMMM d일", "yMMMMEEEEd", "y년 MMMM d일 EEEE", "yQQQ", "y년 QQQ", "yQQQQ", "y년 QQQQ", "H", "H시", "Hm", "HH:mm", "Hms", "H시 m분 s초", "j", "a h시", "jm", "a h:mm", "jms", "a h:mm:ss", "jmv", "a h:mm v", "jmz", "a h:mm z", "jz", "a h시 z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C53() {
      return C53 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd-MM", "MEd", "dd-MM, EEE", "MMM", "LLL", "MMMd", "d-MMM", "MMMEd", "d-MMM, EEE", "MMMM", "LLLL", "MMMMd", "d-MMMM", "MMMMEEEEd", "d-MMMM, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "y-dd-MM", "yMEd", "y-dd-MM, EEE", "yMMM", "y-'ж'. MMM", "yMMMd", "y-'ж'. d-MMM", "yMMMEd", "y-'ж'. d-MMM, EEE", "yMMMM", "y-'ж'., MMMM", "yMMMMd", "y-'ж'., d-MMMM", "yMMMMEEEEd", "y-'ж'., d-MMMM, EEEE", "yQQQ", "y-'ж'., QQQ", "yQQQQ", "y-'ж'., QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C54() {
      return C54 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "EEE", "EEEE", "EEEE", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "y MMMM", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "H", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "H z", "m", "m", "ms", "m:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C55() {
      return C55 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C56() {
      return C56 = dart.constMap(StringL(), StringL(), ["d", "dd", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "MM", "Md", "MM-d", "MEd", "MM-dd, EEE", "MMM", "MM", "MMMd", "MM-dd", "MMMEd", "MM-dd, EEE", "MMMM", "LLLL", "MMMMd", "MMMM d 'd'.", "MMMMEEEEd", "MMMM d 'd'., EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "y-MM-dd", "yMEd", "y-MM-dd, EEE", "yMMM", "y-MM", "yMMMd", "y-MM-dd", "yMMMEd", "y-MM-dd, EEE", "yMMMM", "y 'm'. LLLL", "yMMMMd", "y 'm'. MMMM d 'd'.", "yMMMMEEEEd", "y 'm'. MMMM d 'd'., EEEE", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm; v", "jmz", "HH:mm; z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C57() {
      return C57 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd.MM.", "MEd", "EEE, dd.MM.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE, d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE, d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y. 'g'.", "yM", "MM.y.", "yMd", "y.MM.d.", "yMEd", "EEE, d.M.y.", "yMMM", "y. 'g'. MMM", "yMMMd", "y. 'g'. d. MMM", "yMMMEd", "EEE, y. 'g'. d. MMM", "yMMMM", "y. 'g'. MMMM", "yMMMMd", "y. 'gada' d. MMMM", "yMMMMEEEEd", "EEEE, y. 'gada' d. MMMM", "yQQQ", "y. 'g'. QQQ", "yQQQQ", "y. 'g'. QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C58() {
      return C58 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M", "MEd", "EEE, d.M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M.y", "yMd", "d.M.y", "yMEd", "EEE, d.M.y", "yMMM", "MMM y 'г'.", "yMMMd", "d MMM y 'г'.", "yMMMEd", "EEE, d MMM y 'г'.", "yMMMM", "MMMM y 'г'.", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y 'г'.", "yQQQQ", "QQQQ y 'г'.", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C59() {
      return C59 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "d/M, EEE", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "MMM d, EEE", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "MMMM d, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "d/M/y", "yMEd", "d-M-y, EEE", "yMMM", "y MMM", "yMMMd", "y MMM d", "yMMMEd", "y MMM d, EEE", "yMMMM", "y MMMM", "yMMMMd", "y, MMMM d", "yMMMMEEEEd", "y, MMMM d, EEEE", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C60() {
      return C60 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "MM/dd", "MEd", "MM/dd, EEE", "MMM", "LLL", "MMMd", "MMM'ын' d", "MMMEd", "MMM'ын' d, EEE", "MMMM", "LLLL", "MMMMd", "MMM'ын' d", "MMMMEEEEd", "MMMM'ын' d, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y M", "yMd", "y.MM.dd", "yMEd", "y.MM.dd, EEE", "yMMM", "y 'оны' MMM", "yMMMd", "y.MM.dd", "yMMMEd", "y.MM.dd, EEE", "yMMMM", "y 'оны' MMM", "yMMMMd", "y.MM.dd", "yMMMMEEEEd", "y.MM.dd, EEEE", "yQQQ", "y QQQ", "yQQQQ", "y 'оны' QQQQ", "H", "HH 'ц'", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH 'ц'", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH 'ц' z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C61() {
      return C61 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd.MM", "MEd", "EEE, dd.MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "dd.MM.y", "yMEd", "EEE, dd.MM.y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C62() {
      return C62 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM, y", "yMMMEd", "EEE, d, MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM, y", "yMMMMEEEEd", "EEEE, d MMMM, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C63() {
      return C63 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d-M", "MEd", "EEE, d-M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M-y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C64() {
      return C64 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "MM-dd", "MEd", "EEE, M-d", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "EEE, d 'ta'’ MMM", "MMMM", "LLLL", "MMMMd", "d 'ta'’ MMMM", "MMMMEEEEd", "EEEE, d 'ta'’ MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d 'ta'’ MMM, y", "yMMMEd", "EEE, d 'ta'’ MMM, y", "yMMMM", "MMMM y", "yMMMMd", "d 'ta'’ MMMM y", "yMMMMEEEEd", "EEEE, d 'ta'’ MMMM y", "yQQQ", "QQQ - y", "yQQQQ", "QQQQ - y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C65() {
      return C65 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "cccနေ့", "EEEE", "ccccနေ့", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "d/M၊ EEE", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "MMM d၊ EEE", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "MMMM d ရက် EEEEနေ့", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "dd-MM-y", "yMEd", "d/M/y၊ EEE", "yMMM", "MMM y", "yMMMd", "y၊ MMM d", "yMMMEd", "y၊ MMM d၊ EEE", "yMMMM", "y MMMM", "yMMMMd", "y၊ d MMMM", "yMMMMEEEEd", "y၊ MMMM d၊ EEEE", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "v HH:mm", "jmz", "z HH:mm", "jz", "z HH", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C66() {
      return C66 = dart.constMap(StringL(), StringL(), ["d", "d.", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L.", "Md", "d.M.", "MEd", "EEE d.M.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M.y", "yMd", "d.M.y", "yMEd", "EEE d.MM.y", "yMMM", "MMM y", "yMMMd", "d. MMM y", "yMMMEd", "EEE d. MMM y", "yMMMM", "MMMM y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C67() {
      return C67 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "MM-dd", "MEd", "MM-dd, EEE", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "MMM d, EEE", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "MMMM d, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "y-MM-dd", "yMEd", "y-MM-dd, EEE", "yMMM", "y MMM", "yMMMd", "y MMM d", "yMMMEd", "y MMM d, EEE", "yMMMM", "y MMMM", "yMMMMd", "y MMMM d", "yMMMMEEEEd", "y MMMM d, EEEE", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C68() {
      return C68 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d-M", "MEd", "EEE d-M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M-y", "yMd", "d-M-y", "yMEd", "EEE d-M-y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C69() {
      return C69 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, dd-MM.", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C70() {
      return C70 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.MM", "MEd", "EEE, d.MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "d.MM.y", "yMEd", "EEE, d.MM.y", "yMMM", "LLL y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "LLLL y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C71() {
      return C71 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, dd/MM", "MMM", "LLL", "MMMd", "d 'de' MMM", "MMMEd", "EEE, d 'de' MMM", "MMMM", "LLLL", "MMMMd", "d 'de' MMMM", "MMMMEEEEd", "EEEE, d 'de' MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd/MM/y", "yMEd", "EEE, dd/MM/y", "yMMM", "MMM 'de' y", "yMMMd", "d 'de' MMM 'de' y", "yMMMEd", "EEE, d 'de' MMM 'de' y", "yMMMM", "MMMM 'de' y", "yMMMMd", "d 'de' MMMM 'de' y", "yMMMMEEEEd", "EEEE, d 'de' MMMM 'de' y", "yQQQ", "QQQ 'de' y", "yQQQQ", "QQQQ 'de' y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C72() {
      return C72 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd/MM", "MEd", "EEE, dd/MM", "MMM", "LLL", "MMMd", "d/MM", "MMMEd", "EEE, d/MM", "MMMM", "LLLL", "MMMMd", "d 'de' MMMM", "MMMMEEEEd", "cccc, d 'de' MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd/MM/y", "yMEd", "EEE, dd/MM/y", "yMMM", "MM/y", "yMMMd", "d/MM/y", "yMMMEd", "EEE, d/MM/y", "yMMMM", "MMMM 'de' y", "yMMMMd", "d 'de' MMMM 'de' y", "yMMMMEEEEd", "EEEE, d 'de' MMMM 'de' y", "yQQQ", "QQQQ 'de' y", "yQQQQ", "QQQQ 'de' y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C73() {
      return C73 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd.MM", "MEd", "EEE, dd.MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "ccc, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "cccc, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "dd.MM.y", "yMEd", "ccc, dd.MM.y 'г'.", "yMMM", "LLL y 'г'.", "yMMMd", "d MMM y 'г'.", "yMMMEd", "EEE, d MMM y 'г'.", "yMMMM", "LLLL y 'г'.", "yMMMMd", "d MMMM y 'г'.", "yMMMMEEEEd", "EEEE, d MMMM y 'г'.", "yQQQ", "QQQ y 'г'.", "yQQQQ", "QQQQ y 'г'.", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "H:mm v", "jmz", "H:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C74() {
      return C74 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "EEE", "EEEE", "EEEE", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M.", "MEd", "EEE, d.M.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE, d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y.", "yM", "M.y.", "yMd", "d.M.y.", "yMEd", "EEE, d.M.y.", "yMMM", "MMM y.", "yMMMd", "d. MMM y.", "yMMMEd", "EEE, d. MMM y.", "yMMMM", "MMMM y.", "yMMMMd", "d. MMMM y.", "yMMMMEEEEd", "EEEE, d. MMMM y.", "yQQQ", "QQQ y.", "yQQQQ", "QQQQ y.", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C75() {
      return C75 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "M-d", "MEd", "M-d, EEE", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "MMM d EEE", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "MMMM d EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-M", "yMd", "y-M-d", "yMEd", "y-M-d, EEE", "yMMM", "y MMM", "yMMMd", "y MMM d", "yMMMEd", "y MMM d, EEE", "yMMMM", "y MMMM", "yMMMMd", "y MMMM d", "yMMMMEEEEd", "y MMMM d, EEEE", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH.mm", "Hms", "HH.mm.ss", "j", "HH", "jm", "HH.mm", "jms", "HH.mm.ss", "jmv", "HH.mm v", "jmz", "HH.mm z", "jz", "HH z", "m", "m", "ms", "mm.ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C76() {
      return C76 = dart.constMap(StringL(), StringL(), ["d", "d.", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L.", "Md", "d. M.", "MEd", "EEE d. M.", "MMM", "LLL", "MMMd", "d. M.", "MMMEd", "EEE d. M.", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d. M. y", "yMEd", "EEE d. M. y", "yMMM", "M/y", "yMMMd", "d. M. y", "yMMMEd", "EEE d. M. y", "yMMMM", "LLLL y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "H", "Hm", "H:mm", "Hms", "H:mm:ss", "j", "H", "jm", "H:mm", "jms", "H:mm:ss", "jmv", "H:mm v", "jmz", "H:mm z", "jz", "H z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C77() {
      return C77 = dart.constMap(StringL(), StringL(), ["d", "d.", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d. M.", "MEd", "EEE, d. M.", "MMM", "LLL", "MMMd", "d. MMM", "MMMEd", "EEE, d. MMM", "MMMM", "LLLL", "MMMMd", "d. MMMM", "MMMMEEEEd", "EEEE, d. MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d. M. y", "yMEd", "EEE, d. M. y", "yMMM", "MMM y", "yMMMd", "d. MMM y", "yMMMEd", "EEE, d. MMM y", "yMMMM", "MMMM y", "yMMMMd", "d. MMMM y", "yMMMMEEEEd", "EEEE, d. MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH'h'", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH'h'", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH'h' z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C78() {
      return C78 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d.M", "MEd", "EEE, d.M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M.y", "yMd", "d.M.y", "yMEd", "EEE, d.M.y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ, y", "yQQQQ", "QQQQ, y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a, v", "jmz", "h:mm a, z", "jz", "h a, z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C79() {
      return C79 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "y-MM-dd", "yMEd", "EEE, y-MM-dd", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C80() {
      return C80 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE, d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE, MMM d, y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "y QQQ", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C81() {
      return C81 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "dd-MM, EEE", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "MMM d, EEE", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "MMMM d, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM, y", "yMMMEd", "EEE, d MMM, y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM, y", "yMMMMEEEEd", "EEEE, d MMMM, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "a h", "jm", "a h:mm", "jms", "a h:mm:ss", "jmv", "a h:mm v", "jmz", "a h:mm z", "jz", "a h z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C82() {
      return C82 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "d/M, EEE", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "d MMM, EEE", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "d MMMM, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "d/M/y, EEE", "yMMM", "MMM y", "yMMMd", "d, MMM y", "yMMMEd", "d MMM, y, EEE", "yMMMM", "MMMM y", "yMMMMd", "d MMMM, y", "yMMMMEEEEd", "d, MMMM y, EEEE", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C83() {
      return C83 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEEที่ d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM G y", "yMMMMd", "d MMMM G y", "yMMMMEEEEd", "EEEEที่ d MMMM G y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ G y", "H", "HH", "Hm", "HH:mm น.", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm น.", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C84() {
      return C84 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "d/MM EEE", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "d MMMM EEE", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "d MMMM EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM/y", "yMd", "dd.MM.y", "yMEd", "d.M.y EEE", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "d MMM y EEE", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "d MMMM y EEEE", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C85() {
      return C85 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "LL", "Md", "dd.MM", "MEd", "EEE, dd.MM", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "dd.MM.y", "yMEd", "EEE, dd.MM.y", "yMMM", "LLL y", "yMMMd", "d MMM y", "yMMMEd", "EEE, d MMM y", "yMMMM", "LLLL y", "yMMMMd", "d MMMM y 'р'.", "yMMMMEEEEd", "EEEE, d MMMM y 'р'.", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y 'р'.", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C86() {
      return C86 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE، d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE، d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE، d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE، d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM، y", "yMMMEd", "EEE، d MMM، y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM، y", "yMMMMEEEEd", "EEEE، d MMMM، y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "h a", "jm", "h:mm a", "jms", "h:mm:ss a", "jmv", "h:mm a v", "jmz", "h:mm a z", "jz", "h a z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C87() {
      return C87 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "LL", "Md", "dd/MM", "MEd", "EEE, dd/MM", "MMM", "LLL", "MMMd", "d-MMM", "MMMEd", "EEE, d-MMM", "MMMM", "LLLL", "MMMMd", "d-MMMM", "MMMMEEEEd", "EEEE, d-MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "dd/MM/y", "yMEd", "EEE, dd/MM/y", "yMMM", "MMM, y", "yMMMd", "d-MMM, y", "yMMMEd", "EEE, d-MMM, y", "yMMMM", "MMMM, y", "yMMMMd", "d-MMMM, y", "yMMMMEEEEd", "EEEE, d-MMMM, y", "yQQQ", "y, QQQ", "yQQQQ", "y, QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm (v)", "jmz", "HH:mm (z)", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C88() {
      return C88 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd/M", "MEd", "EEE, dd/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE, d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE, d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE, dd/M/y", "yMMM", "MMM y", "yMMMd", "d MMM, y", "yMMMEd", "EEE, d MMM, y", "yMMMM", "MMMM 'năm' y", "yMMMMd", "d MMMM, y", "yMMMMEEEEd", "EEEE, d MMMM, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ 'năm' y", "H", "HH", "Hm", "H:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "H:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C89() {
      return C89 = dart.constMap(StringL(), StringL(), ["d", "d日", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "M月", "Md", "M/d", "MEd", "M/dEEE", "MMM", "LLL", "MMMd", "M月d日", "MMMEd", "M月d日EEE", "MMMM", "LLLL", "MMMMd", "M月d日", "MMMMEEEEd", "M月d日EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y年", "yM", "y年M月", "yMd", "y/M/d", "yMEd", "y/M/dEEE", "yMMM", "y年M月", "yMMMd", "y年M月d日", "yMMMEd", "y年M月d日EEE", "yMMMM", "y年M月", "yMMMMd", "y年M月d日", "yMMMMEEEEd", "y年M月d日EEEE", "yQQQ", "y年第Q季度", "yQQQQ", "y年第Q季度", "H", "H时", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "ah时", "jm", "ah:mm", "jms", "ah:mm:ss", "jmv", "v ah:mm", "jmz", "z ah:mm", "jz", "zah时", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C90() {
      return C90 = dart.constMap(StringL(), StringL(), ["d", "d日", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "M月", "Md", "d/M", "MEd", "d/M（EEE）", "MMM", "LLL", "MMMd", "M月d日", "MMMEd", "M月d日EEE", "MMMM", "LLLL", "MMMMd", "M月d日", "MMMMEEEEd", "M月d日EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y年", "yM", "M/y", "yMd", "d/M/y", "yMEd", "d/M/y（EEE）", "yMMM", "y年M月", "yMMMd", "y年M月d日", "yMMMEd", "y年M月d日EEE", "yMMMM", "y年M月", "yMMMMd", "y年M月d日", "yMMMMEEEEd", "y年M月d日EEEE", "yQQQ", "y年QQQ", "yQQQQ", "y年QQQQ", "H", "H時", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "ah時", "jm", "ah:mm", "jms", "ah:mm:ss", "jmv", "ah:mm [v]", "jmz", "ah:mm [z]", "jz", "ah時 z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C91() {
      return C91 = dart.constMap(StringL(), StringL(), ["d", "d日", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "M月", "Md", "M/d", "MEd", "M/d（EEE）", "MMM", "LLL", "MMMd", "M月d日", "MMMEd", "M月d日 EEE", "MMMM", "LLLL", "MMMMd", "M月d日", "MMMMEEEEd", "M月d日 EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y年", "yM", "y/M", "yMd", "y/M/d", "yMEd", "y/M/d（EEE）", "yMMM", "y年M月", "yMMMd", "y年M月d日", "yMMMEd", "y年M月d日 EEE", "yMMMM", "y年M月", "yMMMMd", "y年M月d日", "yMMMMEEEEd", "y年M月d日 EEEE", "yQQQ", "y年QQQ", "yQQQQ", "y年QQQQ", "H", "H時", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "ah時", "jm", "ah:mm", "jms", "ah:mm:ss", "jmv", "ah:mm [v]", "jmz", "ah:mm [z]", "jz", "ah時 z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C92() {
      return C92 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "MM-dd", "MEd", "MM-dd, EEE", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "EEE, MMM d", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "EEEE, MMMM d", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "y-MM-dd", "yMEd", "y-MM-dd, EEE", "yMMM", "MMM y", "yMMMd", "MMM d, y", "yMMMEd", "EEE, MMM d, y", "yMMMM", "MMMM y", "yMMMMd", "MMMM d, y", "yMMMMEEEEd", "EEEE, MMMM d, y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C93() {
      return C93 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "EEE", "EEEE", "EEEE", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "dd.MM.", "MEd", "EEE, dd.MM.", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "MM.y", "yMd", "dd.MM.y", "yMEd", "EEE, dd.MM.y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH 'h'", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH 'h'", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH 'h' z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C94() {
      return C94 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "d/M", "MEd", "EEE d/M", "MMM", "LLL", "MMMd", "d MMM", "MMMEd", "EEE d MMM", "MMMM", "LLLL", "MMMMd", "d MMMM", "MMMMEEEEd", "EEEE d MMMM", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "M/y", "yMd", "d/M/y", "yMEd", "EEE d/M/y", "yMMM", "MMM y", "yMMMd", "d MMM y", "yMMMEd", "EEE d MMM y", "yMMMM", "MMMM y", "yMMMMd", "d MMMM y", "yMMMMEEEEd", "EEEE, d MMMM y", "yQQQ", "QQQ y", "yQQQQ", "QQQQ y", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH z", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C95() {
      return C95 = dart.constMap(StringL(), StringL(), ["d", "d", "E", "ccc", "EEEE", "cccc", "LLL", "LLL", "LLLL", "LLLL", "M", "L", "Md", "MM-dd", "MEd", "MM-dd, EEE", "MMM", "LLL", "MMMd", "MMM d", "MMMEd", "MMM d, EEE", "MMMM", "LLLL", "MMMMd", "MMMM d", "MMMMEEEEd", "MMMM d, EEEE", "QQQ", "QQQ", "QQQQ", "QQQQ", "y", "y", "yM", "y-MM", "yMd", "y-MM-dd", "yMEd", "y-MM-dd, EEE", "yMMM", "y MMM", "yMMMd", "y MMM d", "yMMMEd", "y MMM d, EEE", "yMMMM", "y MMMM", "yMMMMd", "د y د MMMM d", "yMMMMEEEEd", "EEEE د y د MMMM d", "yQQQ", "y QQQ", "yQQQQ", "y QQQQ", "H", "HH", "Hm", "HH:mm", "Hms", "HH:mm:ss", "j", "HH", "jm", "HH:mm", "jms", "HH:mm:ss", "jmv", "HH:mm v", "jmz", "HH:mm z", "jz", "HH (z)", "m", "m", "ms", "mm:ss", "s", "s", "v", "v", "z", "z", "zzzz", "zzzz", "ZZZZ", "ZZZZ"]);
    },
    get C0() {
      return C0 = dart.constMap(dart.dynamic, dart.dynamic, ["af", C1 || CT.C1, "am", C2 || CT.C2, "ar", C3 || CT.C3, "ar_DZ", C3 || CT.C3, "ar_EG", C3 || CT.C3, "az", C4 || CT.C4, "be", C5 || CT.C5, "bg", C6 || CT.C6, "bn", C7 || CT.C7, "br", C8 || CT.C8, "bs", C9 || CT.C9, "ca", C10 || CT.C10, "chr", C11 || CT.C11, "cs", C12 || CT.C12, "cy", C13 || CT.C13, "da", C14 || CT.C14, "de", C15 || CT.C15, "de_AT", C15 || CT.C15, "de_CH", C15 || CT.C15, "el", C16 || CT.C16, "en", C11 || CT.C11, "en_AU", C17 || CT.C17, "en_CA", C18 || CT.C18, "en_GB", C19 || CT.C19, "en_IE", C20 || CT.C20, "en_IN", C21 || CT.C21, "en_SG", C22 || CT.C22, "en_US", C11 || CT.C11, "en_ZA", C23 || CT.C23, "es", C24 || CT.C24, "es_419", C25 || CT.C25, "es_ES", C24 || CT.C24, "es_MX", C26 || CT.C26, "es_US", C27 || CT.C27, "et", C28 || CT.C28, "eu", C29 || CT.C29, "fa", C30 || CT.C30, "fi", C31 || CT.C31, "fil", C11 || CT.C11, "fr", C32 || CT.C32, "fr_CA", C33 || CT.C33, "ga", C34 || CT.C34, "gl", C35 || CT.C35, "gsw", C36 || CT.C36, "gu", C37 || CT.C37, "haw", C38 || CT.C38, "he", C39 || CT.C39, "hi", C40 || CT.C40, "hr", C41 || CT.C41, "hu", C42 || CT.C42, "hy", C43 || CT.C43, "id", C44 || CT.C44, "in", C44 || CT.C44, "is", C45 || CT.C45, "it", C46 || CT.C46, "iw", C39 || CT.C39, "ja", C47 || CT.C47, "ka", C48 || CT.C48, "kk", C49 || CT.C49, "km", C50 || CT.C50, "kn", C51 || CT.C51, "ko", C52 || CT.C52, "ky", C53 || CT.C53, "ln", C54 || CT.C54, "lo", C55 || CT.C55, "lt", C56 || CT.C56, "lv", C57 || CT.C57, "mk", C58 || CT.C58, "ml", C59 || CT.C59, "mn", C60 || CT.C60, "mo", C61 || CT.C61, "mr", C62 || CT.C62, "ms", C63 || CT.C63, "mt", C64 || CT.C64, "my", C65 || CT.C65, "nb", C66 || CT.C66, "ne", C67 || CT.C67, "nl", C68 || CT.C68, "no", C66 || CT.C66, "no_NO", C66 || CT.C66, "or", C11 || CT.C11, "pa", C69 || CT.C69, "pl", C70 || CT.C70, "pt", C71 || CT.C71, "pt_BR", C71 || CT.C71, "pt_PT", C72 || CT.C72, "ro", C61 || CT.C61, "ru", C73 || CT.C73, "sh", C74 || CT.C74, "si", C75 || CT.C75, "sk", C76 || CT.C76, "sl", C77 || CT.C77, "sq", C78 || CT.C78, "sr", C74 || CT.C74, "sr_Latn", C74 || CT.C74, "sv", C79 || CT.C79, "sw", C80 || CT.C80, "ta", C81 || CT.C81, "te", C82 || CT.C82, "th", C83 || CT.C83, "tl", C11 || CT.C11, "tr", C84 || CT.C84, "uk", C85 || CT.C85, "ur", C86 || CT.C86, "uz", C87 || CT.C87, "vi", C88 || CT.C88, "zh", C89 || CT.C89, "zh_CN", C89 || CT.C89, "zh_HK", C90 || CT.C90, "zh_TW", C91 || CT.C91, "zu", C92 || CT.C92, "en_ISO", C11 || CT.C11, "en_MY", C22 || CT.C22, "fr_CH", C93 || CT.C93, "it_CH", C94 || CT.C94, "ps", C95 || CT.C95]);
    }
  }, false);
  var C1;
  var C2;
  var C3;
  var C4;
  var C5;
  var C6;
  var C7;
  var C8;
  var C9;
  var C10;
  var C11;
  var C12;
  var C13;
  var C14;
  var C15;
  var C16;
  var C17;
  var C18;
  var C19;
  var C20;
  var C21;
  var C22;
  var C23;
  var C24;
  var C25;
  var C26;
  var C27;
  var C28;
  var C29;
  var C30;
  var C31;
  var C32;
  var C33;
  var C34;
  var C35;
  var C36;
  var C37;
  var C38;
  var C39;
  var C40;
  var C41;
  var C42;
  var C43;
  var C44;
  var C45;
  var C46;
  var C47;
  var C48;
  var C49;
  var C50;
  var C51;
  var C52;
  var C53;
  var C54;
  var C55;
  var C56;
  var C57;
  var C58;
  var C59;
  var C60;
  var C61;
  var C62;
  var C63;
  var C64;
  var C65;
  var C66;
  var C67;
  var C68;
  var C69;
  var C70;
  var C71;
  var C72;
  var C73;
  var C74;
  var C75;
  var C76;
  var C77;
  var C78;
  var C79;
  var C80;
  var C81;
  var C82;
  var C83;
  var C84;
  var C85;
  var C86;
  var C87;
  var C88;
  var C89;
  var C90;
  var C91;
  var C92;
  var C93;
  var C94;
  var C95;
  var C0;
  date_time_patterns.dateTimePatternMap = function dateTimePatternMap() {
    return C0 || CT.C0;
  };
  dart.trackLibraries("packages/intl/date_time_patterns", {
    "package:intl/date_time_patterns.dart": date_time_patterns
  }, {
  }, '{"version":3,"sourceRoot":"","sources":["date_time_patterns.dart"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;AAe4B;EAi8KvB","file":"date_time_patterns.ddc.js"}');
  // Exports:
  return {
    date_time_patterns: date_time_patterns
  };
}));

//# sourceMappingURL=date_time_patterns.ddc.js.map
